"Resource/UI/Scoreboard.res"
    {
	"scores"
	{
		"ControlName"	"CTFClientScoreBoardDialog"
		"fieldName"	"scoreinfo"
		"xpos"	"cs-0.5"
		"ypos"	"31"
		"wide"	"f0"
		"tall"	"f0"
		"autoResize"	"0"
		"pinCorner"	"0"
		"visible"	"1"
		"enabled"	"1"
		"tabPosition"	"0"
		"medal_width"	"25"
		"avatar_width"	"55"
		"spacer"	"5"
		"name_width"	"140"
		"nemesis_width"	"20"
		"class_width"	"20"
		"score_width"	"25"
		"ping_width"	"25"
		"killstreak_width"	"15"
		"killstreak_image_width"	"15"
		"medal_width_minmode"	"0"
	}
	"BlueLine"
	{
		"ControlName"	"EditablePanel"
		"fieldName"	"BlueLine"
		"xpos"	"0"
		"ypos"	"0"
		"zpos"	"1"
		"wide"	"2"
		"tall"	"35"
		"autoResize"	"0"
		"autoResize"	"0"
		"pinCorner"	"0"
		"pinCorner"	"0"
		"visible"	"1"
		"enabled"	"1"
		"PaintBackgroundType"	"0"
		"paintbackground"	"1"
		"bgcolor_override"	"HUDBlueTeamSolid"
		"pin_to_sibling"	"BlueBG"
		"pin_corner_to_sibling"	"PIN_TOPRIGHT"
		"pin_to_sibling_corner"	"PIN_TOPRIGHT"
		"if_mvm"
		{
			"visible"	"0"
		}
	}
	"BlueBG"
	{
		"ControlName"	"EditablePanel"
		"fieldName"	"BlueBG"
		"xpos"	"c-291"
		"ypos"	"50"
		"zpos"	"-1"
		"wide"	"290"
		"tall"	"35"
		"visible"	"1"
		"enabled"	"1"
		"bgcolor_override"	"Black"
		"PaintBackgroundType"	"2"
		"if_mvm"
		{
			"ypos"	"100"
			"visible"	"0"
		}
	}
	"BluePlayerBG"
	{
		"ControlName"	"EditablePanel"
		"fieldName"	"BluePlayerBG"
		"xpos"	"0"
		"ypos"	"2"
		"zpos"	"2"
		"wide"	"290"
		"wide_minmode"	"0"
		"tall"	"270"
		"visible"	"1"
		"enabled"	"1"
		"bgcolor_override"	"25 25 25 200"
		"PaintBackgroundType"	"2"
		"pin_to_sibling"	"ServerBackground"
		"pin_corner_to_sibling"	"PIN_TOPLEFT"
		"pin_to_sibling_corner"	"PIN_BOTTOMLEFT"
		"if_mvm"
		{
			"visible"	"0"
		}
	}
	"BlueTeamName"
	{
		"ControlName"	"CExLabel"
		"fieldName"	"BlueTeamName"
		"font"	"Product18Bold"
		"labelText"	"%blueteamname%"
		"textAlignment"	"west"
		"xpos"	"0"
		"ypos"	"-4"
		"wide"	"250"
		"tall"	"22"
		"autoResize"	"0"
		"pinCorner"	"0"
		"visible"	"1"
		"enabled"	"1"
		"fgcolor"	"arekkBlueS"
		"TextInsetX"	"15"
		"pin_to_sibling"	"BlueBG"
		"pin_corner_to_sibling"	"PIN_TOPLEFT"
		"pin_to_sibling_corner"	"PIN_TOPLEFT"
		"if_mvm"
		{
			"visible"	"0"
		}
	}
	"BlueTeamScore"
	{
		"ControlName"	"CExLabel"
		"fieldName"	"BlueTeamScore"
		"font"	"Product36Bold"
		"labelText"	"%blueteamscore%"
		"textAlignment"	"east"
		"xpos"	"0"
		"ypos"	"0"
		"zpos"	"4"
		"wide"	"80"
		"tall"	"35"
		"autoResize"	"0"
		"pinCorner"	"0"
		"visible"	"1"
		"enabled"	"1"
		"fgcolor"	"arekkBlueS"
		"TextInsetX"	"20"
		"pin_to_sibling"	"BlueBG"
		"pin_corner_to_sibling"	"PIN_TOPRIGHT"
		"pin_to_sibling_corner"	"PIN_TOPRIGHT"
		"if_mvm"
		{
			"visible"	"0"
		}
	}
	"BlueTeamPlayerCount"
	{
		"ControlName"	"CExLabel"
		"fieldName"	"BlueTeamPlayerCount"
		"font"	"Product12Bold"
		"labelText"	"%blueteamplayercount%"
		"textAlignment"	"west"
		"xpos"	"0"
		"ypos"	"-6"
		"wide"	"210"
		"tall"	"12"
		"autoResize"	"0"
		"pinCorner"	"0"
		"visible"	"1"
		"enabled"	"1"
		"fgcolor"	"HUDBlueTeamSolid"
		"TextInsetX"	"15"
		"pin_to_sibling"	"BlueTeamName"
		"pin_corner_to_sibling"	"PIN_TOPLEFT"
		"pin_to_sibling_corner"	"PIN_BOTTOMLEFT"
		"if_mvm"
		{
			"visible"	"0"
		}
	}
	"RedLine"
	{
		"ControlName"	"EditablePanel"
		"fieldName"	"RedLine"
		"xpos"	"0"
		"ypos"	"0"
		"zpos"	"1"
		"wide"	"2"
		"tall"	"35"
		"autoResize"	"0"
		"autoResize"	"0"
		"pinCorner"	"0"
		"pinCorner"	"0"
		"visible"	"1"
		"enabled"	"1"
		"PaintBackgroundType"	"0"
		"paintbackground"	"1"
		"bgcolor_override"	"HUDRedTeamSolid"
		"pin_to_sibling"	"RedBG"
		"pin_corner_to_sibling"	"PIN_TOPLEFT"
		"pin_to_sibling_corner"	"PIN_TOPLEFT"
		"if_mvm"
		{
			"visible"	"0"
		}
	}
	"RedBG"
	{
		"ControlName"	"EditablePanel"
		"fieldName"	"RedBG"
		"xpos"	"2"
		"ypos"	"0"
		"zpos"	"-1"
		"wide"	"290"
		"tall"	"35"
		"visible"	"1"
		"enabled"	"1"
		"bgcolor_override"	"Black"
		"PaintBackgroundType"	"2"
		"pin_to_sibling"	"BlueBG"
		"pin_corner_to_sibling"	"PIN_TOPLEFT"
		"pin_to_sibling_corner"	"PIN_TOPRIGHT"
		"if_mvm"
		{
			"visible"	"0"
		}
	}
	"RedPlayerBG"
	{
		"ControlName"	"EditablePanel"
		"fieldName"	"RedPlayerBG"
		"xpos"	"0"
		"ypos"	"2"
		"zpos"	"2"
		"wide"	"290"
		"wide_minmode"	"0"
		"tall"	"270"
		"visible"	"1"
		"enabled"	"1"
		"bgcolor_override"	"25 25 25 200"
		"PaintBackgroundType"	"2"
		"pin_to_sibling"	"ServerTimeBackground"
		"pin_corner_to_sibling"	"PIN_TOPLEFT"
		"pin_to_sibling_corner"	"PIN_BOTTOMLEFT"
		"if_mvm"
		{
			"visible"	"0"
		}
	}
	"RedTeamName"
	{
		"ControlName"	"CExLabel"
		"fieldName"	"RedTeamName"
		"font"	"Product18Bold"
		"labelText"	"%redteamname%"
		"textAlignment"	"east"
		"xpos"	"0"
		"ypos"	"-4"
		"wide"	"250"
		"tall"	"22"
		"autoResize"	"0"
		"pinCorner"	"0"
		"visible"	"1"
		"enabled"	"1"
		"fgcolor"	"arekkRedS"
		"TextInsetX"	"15"
		"pin_to_sibling"	"RedBG"
		"pin_corner_to_sibling"	"PIN_TOPRIGHT"
		"pin_to_sibling_corner"	"PIN_TOPRIGHT"
		"if_mvm"
		{
			"visible"	"0"
		}
	}
	"RedTeamScore"
	{
		"ControlName"	"CExLabel"
		"fieldName"	"RedTeamScore"
		"font"	"Product36Bold"
		"labelText"	"%redteamscore%"
		"textAlignment"	"west"
		"xpos"	"0"
		"ypos"	"0"
		"zpos"	"4"
		"wide"	"80"
		"tall"	"35"
		"autoResize"	"0"
		"pinCorner"	"0"
		"visible"	"1"
		"enabled"	"1"
		"fgcolor"	"arekkRedS"
		"TextInsetX"	"20"
		"pin_to_sibling"	"RedBG"
		"pin_corner_to_sibling"	"PIN_TOPLEFT"
		"pin_to_sibling_corner"	"PIN_TOPLEFT"
		"if_mvm"
		{
			"visible"	"0"
		}
	}
	"RedTeamPlayerCount"
	{
		"ControlName"	"CExLabel"
		"fieldName"	"RedTeamPlayerCount"
		"font"	"Product12Bold"
		"labelText"	"%redteamplayercount%"
		"textAlignment"	"east"
		"xpos"	"0"
		"ypos"	"-6"
		"wide"	"210"
		"tall"	"12"
		"autoResize"	"0"
		"pinCorner"	"0"
		"visible"	"1"
		"enabled"	"1"
		"fgcolor"	"HUDRedTeamSolid"
		"TextInsetX"	"20"
		"pin_to_sibling"	"RedTeamName"
		"pin_corner_to_sibling"	"PIN_TOPRIGHT"
		"pin_to_sibling_corner"	"PIN_BOTTOMRIGHT"
		"if_mvm"
		{
			"visible"	"0"
		}
	}
	"ServerBackground"
	{
		"ControlName"	"EditablePanel"
		"fieldName"	"ServerBackground"
		"xpos"	"0"
		"ypos"	"2"
		"zpos"	"-1"
		"wide"	"290"
		"tall"	"11"
		"visible"	"1"
		"enabled"	"1"
		"bgcolor_override"	"25 25 25 200"
		"PaintBackgroundType"	"2"
		"pin_to_sibling"	"BlueBG"
		"pin_corner_to_sibling"	"PIN_TOPLEFT"
		"pin_to_sibling_corner"	"PIN_BOTTOMLEFT"
		"if_mvm"
		{
			"xpos"	"-25"
			"ypos"	"-55"
			"visible"	"0"
		}
	}
	"ServerLabel"
	{
		"ControlName"	"CExLabel"
		"fieldName"	"ServerLabel"
		"font"	"Product10Bold"
		"labelText"	"%server%"
		"textAlignment"	"west"
		"xpos"	"-5"
		"ypos"	"0"
		"wide"	"280"
		"wide_minmode"	"0"
		"tall"	"11"
		"autoResize"	"0"
		"pinCorner"	"0"
		"visible"	"1"
		"enabled"	"1"
		"pin_to_sibling"	"ServerBackground"
		"pin_corner_to_sibling"	"PIN_TOPLEFT"
		"pin_to_sibling_corner"	"PIN_TOPLEFT"
	}
	"ServerTimeBackground"
	{
		"ControlName"	"EditablePanel"
		"fieldName"	"ServerTimeBackground"
		"xpos"	"0"
		"ypos"	"2"
		"zpos"	"-1"
		"wide"	"290"
		"tall"	"11"
		"visible"	"1"
		"enabled"	"1"
		"bgcolor_override"	"25 25 25 200"
		"PaintBackgroundType"	"2"
		"pin_to_sibling"	"RedBG"
		"pin_corner_to_sibling"	"PIN_TOPRIGHT"
		"pin_to_sibling_corner"	"PIN_BOTTOMRIGHT"
		"if_mvm"
		{
			"visible"	"0"
		}
	}
	"ServerTimeLabel"
	{
		"ControlName"	"CExLabel"
		"fieldName"	"ServerTimeLabel"
		"labelText"	"%servertimeleft%"
		"font"	"Product10Bold"
		"textAlignment"	"east"
		"xpos"	"-5"
		"ypos"	"0"
		"zpos"	"2"
		"wide"	"290"
		"tall"	"11"
		"autoResize"	"0"
		"pinCorner"	"0"
		"visible"	"1"
		"enabled"	"1"
		"pin_to_sibling"	"ServerTimeBackground"
		"pin_corner_to_sibling"	"PIN_TOPRIGHT"
		"pin_to_sibling_corner"	"PIN_TOPRIGHT"
		"if_mvm"
		{
			"visible"	"0"
		}
	}
	"BluePlayerList"
	{
		"ControlName"	"SectionedListPanel"
		"fieldName"	"BluePlayerList"
		"xpos"	"c-290"
		"ypos"	"c-138"
		"zpos"	"20"
		"wide"	"288"
		"tall"	"270"
		"wide_minmode"	"0"
		"pinCorner"	"0"
		"visible"	"1"
		"enabled"	"1"
		"tabPosition"	"0"
		"autoresize"	"3"
		"linespacing"	"16"
		"fgcolor"	"BlueTeamSolid"
		"if_mvm"
		{
			"visible"	"0"
		}
	}
	"RedPlayerList"
	{
		"ControlName"	"SectionedListPanel"
		"fieldName"	"RedPlayerList"
		"xpos"	"c+2"
		"ypos"	"c-138"
		"zpos"	"20"
		"wide"	"288"
		"tall"	"270"
		"wide_minmode"	"0"
		"pinCorner"	"0"
		"visible"	"1"
		"enabled"	"1"
		"tabPosition"	"0"
		"autoresize"	"3"
		"linespacing"	"16"
		"textcolor"	"HUDRedTeamSolid"
		"if_mvm"
		{
			"visible"	"0"
		}
	}
	"Spectators"
	{
		"ControlName"	"CExLabel"
		"fieldName"	"Spectators"
		"font"	"Product10Bold"
		"labelText"	"%spectators%"
		"textAlignment"	"west"
		"xpos"	"-2"
		"ypos"	"0"
		"zpos"	"4"
		"wide"	"f0"
		"wide_minmode"	"0"
		"tall"	"15"
		"autoResize"	"0"
		"pinCorner"	"0"
		"visible"	"1"
		"enabled"	"1"
		"pin_to_sibling"	"StatsBG"
		"pin_corner_to_sibling"	"PIN_TOPLEFT"
		"pin_to_sibling_corner"	"PIN_BOTTOMLEFT"
		"if_mvm"
		{
			"xpos"	"-3"
			"ypos"	"1"
		}
	}
	"StatsBG"
	{
		"ControlName"	"EditablePanel"
		"fieldName"	"StatsBG"
		"xpos"	"0"
		"ypos"	"2"
		"zpos"	"2"
		"wide"	"581"
		"tall"	"50"
		"visible"	"1"
		"enabled"	"1"
		"bgcolor_override"	"25 25 25 200"
		"PaintBackgroundType"	"2"
		"pin_to_sibling"	"BluePlayerBG"
		"pin_corner_to_sibling"	"PIN_TOPLEFT"
		"pin_to_sibling_corner"	"PIN_BOTTOMLEFT"
		"pin_to_sibling_minmode"	"ServerBackground"
		"if_mvm"
		{
			"ypos"	"165"
			"wide"	"270"
			"tall"	"132"
			"pin_to_sibling"	"mapname"
			"pin_corner_to_sibling"	"PIN_TOPRIGHT"
			"pin_to_sibling_corner"	"PIN_BOTTOMRIGHT"
		}
	}
	"SpectatorsInQueue"
	{
		"ControlName"	"CExLabel"
		"fieldName"	"SpectatorsInQueue"
		"font"	"Product10Bold"
		"labelText"	"%waitingtoplay%"
		"textAlignment"	"west"
		"xpos"	"-2"
		"ypos"	"30"
		"zpos"	"4"
		"wide"	"500"
		"wide_minmode"	"0"
		"tall"	"20"
		"autoResize"	"0"
		"pinCorner"	"0"
		"visible"	"1"
		"enabled"	"1"
		"pin_to_sibling"	"StatsBG"
		"pin_corner_to_sibling"	"PIN_BOTTOMLEFT"
		"pin_to_sibling_corner"	"PIN_BOTTOMLEFT"
		"if_mvm"
		{
			"visible"	"0"
		}
	}
	"ClassImage"
	{
		"ControlName"	"ImagePanel"
		"fieldName"	"ClassImage"
		"xpos"	"0"
		"ypos"	"-5"
		"zpos"	"3"
		"wide"	"45"
		"tall"	"45"
		"visible"	"1"
		"enabled"	"1"
		"image"	"../hud/class_scoutred"
		"scaleImage"	"1"
		"pin_to_sibling"	"StatsBG"
		"pin_corner_to_sibling"	"PIN_TOPRIGHT"
		"pin_to_sibling_corner"	"PIN_TOPRIGHT"
		"if_mvm"
		{
			"xpos"	"9999"
		}
	}
	"classmodelpanel"
	{
		"ControlName"	"CTFPlayerModelPanel"
		"fieldName"	"classmodelpanel"
		"xpos"	"0"
		"ypos"	"r300"
		"zpos"	"2"
		"wide"	"150"
		"tall"	"300"
		"autoResize"	"0"
		"pinCorner"	"0"
		"visible"	"1"
		"enabled"	"1"
		"fov"	"13"
		"allow_rot"	"1"
		"render_texture"	"0"
		"model"
		{
			"force_pos"	"1"
			"angles_x"	"0"
			"angles_y"	"200"
			"angles_z"	"0"
			"origin_x"	"200"
			"origin_y"	"2"
			"origin_z"	"-80"
			"frame_origin_x"	"0"
			"frame_origin_y"	"0"
			"frame_origin_z"	"0"
			"spotlight"	"1"
			"modelname"	""
		}
	}
	"PlayerNameBG"
	{
		"ControlName"	"EditablePanel"
		"fieldName"	"PlayerNameBG"
		"xpos"	"0"
		"ypos"	"0"
		"zpos"	"0"
		"wide"	"0"
		"tall"	"0"
		"autoResize"	"0"
		"pinCorner"	"0"
		"visible"	"1"
		"enabled"	"1"
		"border"	"TFThinLineBorder"
		"if_mvm"
		{
			"visible"	"0"
		}
	}
	"PlayerNameLabel"
	{
		"ControlName"	"CExLabel"
		"fieldName"	"PlayerNameLabel"
		"font"	"Product10Bold"
		"labelText"	"%playername%"
		"textAlignment"	"west"
		"xpos"	"0"
		"ypos"	"0"
		"zpos"	"0"
		"wide"	"0"
		"tall"	"0"
		"autoResize"	"0"
		"pinCorner"	"0"
		"visible"	"0"
		"enabled"	"0"
	}
	"ServerLabelNew"
	{
		"ControlName"	"CExLabel"
		"fieldName"	"ServerLabelNew"
		"font"	"ScoreboardVerySmall"
		"labelText"	"%server%"
		"textAlignment"	"east"
		"xpos"	"0"
		"ypos"	"0"
		"zpos"	"0"
		"wide"	"0"
		"tall"	"0"
		"autoResize"	"0"
		"pinCorner"	"0"
		"visible"	"0"
		"enabled"	"0"
	}
	"MapName"
	{
		"ControlName"	"CExLabel"
		"fieldName"	"mapname"
		"font"	"Product10Bold"
		"labelText"	"%mapname%"
		"textAlignment"	"center"
		"xpos"	"-35"
		"ypos"	"-5"
		"zpos"	"5"
		"wide"	"100"
		"tall"	"15"
		"autoResize"	"0"
		"pinCorner"	"0"
		"visible"	"1"
		"enabled"	"1"
		"fgcolor"	"TanLight"
		"pin_to_sibling"	"StatsBG"
		"pin_corner_to_sibling"	"PIN_BOTTOMRIGHT"
		"pin_to_sibling_corner"	"PIN_BOTTOMRIGHT"
		"if_mvm"
		{
			"xpos"	"0"
			"ypos"	"0"
			"wide"	"545"
			"textAlignment"	"east"
			"pin_to_sibling"	"ServerLabel"
			"pin_corner_to_sibling"	"PIN_BOTTOMLEFT"
			"pin_to_sibling_corner"	"PIN_TOPLEFT"
		}
	}
	"HorizontalLine"
	{
		"ControlName"	"ImagePanel"
		"fieldName"	"HorizontalLine"
		"xpos"	"115"
		"ypos"	"367"
		"zpos"	"3"
		"wide"	"0"
		"tall"	"0"
		"autoResize"	"0"
		"pinCorner"	"0"
		"visible"	"0"
		"enabled"	"0"
		"tabPosition"	"0"
		"fillcolor"	"127 127 127 153"
		"PaintBackgroundType"	"0"
	}
	"PlayerScoreLabel"
	{
		"ControlName"	"CExLabel"
		"fieldName"	"PlayerScoreLabel"
		"font"	"Product16Bold"
		"labelText"	"%playerscore%"
		"textAlignment"	"east"
		"xpos"	"5"
		"ypos"	"295"
		"zpos"	"3"
		"wide"	"140"
		"tall"	"20"
		"autoResize"	"0"
		"pinCorner"	"0"
		"visible"	"0"
		"enabled"	"0"
	}
	"LocalPlayerDuelStatsPanel"
	{
		"ControlName"	"EditablePanel"
		"fieldName"	"LocalPlayerDuelStatsPanel"
		"xpos"	"0"
		"ypos"	"0"
		"zpos"	"3"
		"wide"	"585"
		"tall"	"50"
		"autoResize"	"0"
		"pinCorner"	"0"
		"visible"	"1"
		"enabled"	"1"
		"pin_to_sibling"	"StatsBG"
		"if_mvm"
		{
			"visible"	"0"
		}
		"DuelingLabel"
		{
			"ControlName"	"CExLabel"
			"fieldName"	"DuelingLabel"
			"font"	"Product12Bold"
			"labelText"	"#TF_ScoreBoard_Dueling"
			"textAlignment"	"center"
			"xpos"	"250"
			"ypos"	"2"
			"zpos"	"3"
			"wide"	"100"
			"tall"	"20"
			"autoResize"	"0"
			"pinCorner"	"0"
			"visible"	"1"
			"enabled"	"1"
		}
		"DuelingIcon"
		{
			"ControlName"	"ImagePanel"
			"fieldName"	"DuelingIcon"
			"xpos"	"284"
			"ypos"	"15"
			"zpos"	"2"
			"wide"	"32"
			"tall"	"32"
			"visible"	"1"
			"enabled"	"1"
			"image"	"../backpack/player/items/crafting/icon_dueling"
			"scaleImage"	"1"
		}
		"LocalPlayerData"
		{
			"ControlName"	"EditablePanel"
			"fieldName"	"LocalPlayerData"
			"xpos"	"75"
			"ypos"	"0"
			"wide"	"200"
			"tall"	"53"
			"autoResize"	"0"
			"pinCorner"	"0"
			"visible"	"1"
			"enabled"	"1"
			"AvatarBGPanel"
			{
				"ControlName"	"EditablePanel"
				"fieldName"	"AvatarBGPanel"
				"xpos"	"157"
				"ypos"	"7"
				"zpos"	"-1"
				"wide"	"36"
				"tall"	"36"
				"visible"	"1"
				"PaintBackgroundType"	"2"
				"bgcolor_override"	"TextColor"
			}
			"AvatarImage"
			{
				"ControlName"	"CAvatarImagePanel"
				"fieldName"	"AvatarImage"
				"xpos"	"159"
				"ypos"	"9"
				"zpos"	"0"
				"wide"	"32"
				"tall"	"32"
				"visible"	"1"
				"enabled"	"1"
				"image"	""
				"scaleImage"	"1"
				"color_outline"	"HudTimerProgressInActive"
			}
			"AvatarTextLabel"
			{
				"ControlName"	"CExLabel"
				"fieldName"	"AvatarTextLabel"
				"fgcolor"	"TanLight"
				"xpos"	"50"
				"ypos"	"7"
				"zpos"	"2"
				"wide"	"100"
				"tall"	"18"
				"autoResize"	"0"
				"pinCorner"	"0"
				"visible"	"1"
				"enabled"	"1"
				"wrap"	"0"
				"labelText"	"%playername%"
				"textAlignment"	"east"
				"font"	"Product12BoldShadow"
			}
			"Score"
			{
				"ControlName"	"CExLabel"
				"fieldName"	"Score"
				"labelText"	"%score%"
				"textAlignment"	"east"
				"xpos"	"50"
				"ypos"	"20"
				"zpos"	"3"
				"wide"	"100"
				"tall"	"20"
				"autoResize"	"0"
				"pinCorner"	"0"
				"visible"	"1"
				"enabled"	"1"
				"font"	"Product14BoldShadow"
			}
		}
		"OpponentData"
		{
			"ControlName"	"EditablePanel"
			"fieldName"	"OpponentData"
			"xpos"	"325"
			"ypos"	"0"
			"wide"	"200"
			"tall"	"53"
			"autoResize"	"0"
			"pinCorner"	"0"
			"visible"	"1"
			"enabled"	"1"
			"AvatarBGPanel"
			{
				"ControlName"	"EditablePanel"
				"fieldName"	"AvatarBGPanel"
				"xpos"	"7"
				"ypos"	"7"
				"zpos"	"-1"
				"wide"	"36"
				"tall"	"36"
				"visible"	"1"
				"PaintBackgroundType"	"2"
				"bgcolor_override"	"TextColor"
			}
			"AvatarImage"
			{
				"ControlName"	"CAvatarImagePanel"
				"fieldName"	"AvatarImage"
				"xpos"	"9"
				"ypos"	"9"
				"zpos"	"0"
				"wide"	"32"
				"tall"	"32"
				"visible"	"1"
				"enabled"	"1"
				"image"	""
				"scaleImage"	"1"
				"color_outline"	"HudTimerProgressInActive"
			}
			"AvatarTextLabel"
			{
				"ControlName"	"CExLabel"
				"fieldName"	"AvatarTextLabel"
				"fgcolor"	"TanLight"
				"xpos"	"50"
				"ypos"	"7"
				"zpos"	"2"
				"wide"	"100"
				"tall"	"18"
				"autoResize"	"0"
				"pinCorner"	"0"
				"visible"	"1"
				"enabled"	"1"
				"wrap"	"0"
				"labelText"	"%playername%"
				"textAlignment"	"west"
				"font"	"Product10Bold"
			}
			"Score"
			{
				"ControlName"	"CExLabel"
				"fieldName"	"Score"
				"labelText"	"%score%"
				"textAlignment"	"west"
				"xpos"	"50"
				"ypos"	"20"
				"zpos"	"3"
				"wide"	"200"
				"tall"	"20"
				"autoResize"	"0"
				"pinCorner"	"0"
				"visible"	"1"
				"enabled"	"1"
				"font"	"HudFontMediumSmallBold"
			}
		}
	}
	"LocalPlayerStatsPanel"
	{
		"ControlName"	"EditablePanel"
		"fieldName"	"LocalPlayerStatsPanel"
		"xpos"	"0"
		"ypos"	"0"
		"zpos"	"3"
		"wide"	"585"
		"tall"	"50"
		"autoResize"	"0"
		"pinCorner"	"0"
		"visible"	"1"
		"enabled"	"1"
		"pin_to_sibling"	"StatsBG"
		"if_mvm"
		{
			"wide"	"270"
			"tall"	"132"
		}
		"KillsLabel"
		{
			"ControlName"	"CExLabel"
			"fieldName"	"KillsLabel"
			"font"	"Product16BoldOutline"
			"labelText"	":"
			"textAlignment"	"center"
			"xpos"	"50"
			"ypos"	"0"
			"zpos"	"3"
			"wide"	"20"
			"tall"	"50"
			"autoResize"	"0"
			"pinCorner"	"0"
			"visible"	"1"
			"enabled"	"1"
			"fgcolor"	"TanLight"
			"pin_to_sibling"	"StatsBG"
			"pin_corner_to_sibling"	"PIN_TOPLEFT"
			"pin_to_sibling_corner"	"PIN_TOPLEFT"
			"if_mvm"
			{
				"xpos"	"117"
				"ypos"	"0"
			}
		}
		"Kills"
		{
			"ControlName"	"CExLabel"
			"fieldName"	"Kills"
			"font"	"Product34Bold"
			"labelText"	"%kills%"
			"textAlignment"	"east"
			"xpos"	"0"
			"ypos"	"0"
			"zpos"	"3"
			"wide"	"80"
			"tall"	"50"
			"autoResize"	"0"
			"pinCorner"	"0"
			"visible"	"0"
			"enabled"	"0"
			"fgcolor"	"TanLight"
			"pin_to_sibling"	"KillsLabel"
			"pin_corner_to_sibling"	"PIN_TOPRIGHT"
			"pin_to_sibling_corner"	"PIN_TOPLEFT"
		}
		"Kills2"
		{
			"ControlName"	"CExLabel"
			"fieldName"	"Kills2"
			"font"	"Product34Bold"
			"labelText"	"%kills%"
			"textAlignment"	"east"
			"xpos"	"0"
			"ypos"	"0"
			"zpos"	"3"
			"wide"	"80"
			"tall"	"50"
			"autoResize"	"0"
			"pinCorner"	"0"
			"visible"	"1"
			"enabled"	"1"
			"fgcolor"	"75 255 83 255"
			"pin_to_sibling"	"Kills"
		}
		"DeathsLabel"
		{
			"ControlName"	"CExLabel"
			"fieldName"	"DeathsLabel"
			"font"	"Product12BoldShadow"
			"labelText"	"#TF_ScoreBoard_DeathsLabel"
			"textAlignment"	"east"
			"xpos"	"0"
			"ypos"	"0"
			"zpos"	"0"
			"wide"	"0"
			"tall"	"0"
			"autoResize"	"0"
			"pinCorner"	"0"
			"visible"	"1"
			"enabled"	"1"
		}
		"Deaths"
            {
                "ControlName"	"CExLabel"
                "fieldName"	"Deaths"
                "font"	"Product34Bold"
                "labelText"	"%deaths%"
                "textAlignment"	"west"
                "xpos"	"0"
                "ypos"	"0"
                "zpos"	"3"
                "wide"	"80"
                "tall"	"50"
                "autoResize"	"0"
                "pinCorner"	"0"
                "visible"	"0"
                "enabled"	"0"
                "fgcolor"	"TanLight"
                "pin_to_sibling"	"KillsLabel"
                "pin_corner_to_sibling"	"PIN_TOPLEFT"
                "pin_to_sibling_corner"	"PIN_TOPRIGHT"
            }
		"Deaths2"
            {
                "ControlName"	"CExLabel"
                "fieldName"	"Deaths2"
                "font"	"Product34Bold"
                "labelText"	"%deaths%"
                "textAlignment"	"west"
                "xpos"	"0"
                "ypos"	"0"
                "zpos"	"3"
                "wide"	"80"
                "tall"	"50"
                "autoResize"	"0"
                "pinCorner"	"0"
                "visible"	"1"
                "enabled"	"1"
                "fgcolor"	"255 75 75 255"
                "pin_to_sibling"	"Deaths"
            }

		"GameType"
		{
			"ControlName"	"CExLabel"
			"fieldName"	"gametype"
			"font"	"Product10Bold"
			"labelText"	"%gametype%"
			"textAlignment"	"east"
			"xpos"	"5"
			"ypos"	"10"
			"zpos"	"3"
			"wide"	"585"
			"tall"	"20"
			"autoResize"	"0"
			"pinCorner"	"0"
			"visible"	"0"
			"enabled"	"0"
			"fgcolor"	"TanLight"
        }

            "AssistsLabel"
            {
                "ControlName"	"CExLabel"
                "fieldName"	"AssistsLabel"
                "font"	"Product10Bold"
                "labelText"	"#TF_ScoreBoard_AssistsLabel"
                "textAlignment"	"east"
                "xpos"	"140"
                "ypos"	"2"
                "zpos"	"3"
                "wide"	"50"
                "tall"	"20"
                "autoResize"	"0"
                "pinCorner"	"0"
                "visible"	"1"
                "enabled"	"1"
                "fgcolor"   "Yellow"
                "pin_to_sibling"	"StatsBG"
                "pin_corner_to_sibling"	"PIN_TOPRIGHT"
                "pin_to_sibling_corner"	"PIN_TOPRIGHT"
                "if_mvm"
                {
                    "font"	"Product12Bold"
                    "xpos"	"0"
                    "ypos"	"50"
                }
            }
            "Assists"
            {
                "ControlName"	"CExLabel"
                "fieldName"	"Assists"
                "font"	"Product10Bold"
                "labelText"	"%assists%"
                "textAlignment"	"west"
                "xpos"	"35"
                "ypos"	"0"
                "zpos"	"3"
                "wide"	"30"
                "tall"	"20"
                "autoResize"	"0"
                "pinCorner"	"0"
                "visible"	"0"
                "enabled"	"0"
                "pin_to_sibling"	"AssistsLabel"
                "pin_corner_to_sibling"	"PIN_TOPRIGHT"
                "pin_to_sibling_corner"	"PIN_TOPRIGHT"
            }
            "Assists2"
            {
                "ControlName"	"CExLabel"
                "fieldName"	"Assists2"
                "font"	"Product10Bold"
                "labelText"	"%assists%"
                "textAlignment"	"west"
                "xpos"	"0"
                "ypos"	"0"
                "zpos"	"3"
                "wide"	"30"
                "tall"	"20"
                "autoResize"	"0"
                "pinCorner"	"0"
                "visible"	"1"
                "enabled"	"1"
                "fgcolor"   "Yellow"
                "pin_to_sibling"	"Assists"
                "pin_corner_to_sibling"	"PIN_TOPRIGHT"
                "pin_to_sibling_corner"	"PIN_TOPRIGHT"
                "if_mvm"
                {
                    "font"	"Product10Bold"
                }
            }
            "DestructionLabel"
            {
                "ControlName"	"CExLabel"
                "fieldName"	"DestructionLabel"
                "font"	"Product10Bold"
                "labelText"	"#TF_ScoreBoard_DestructionLabel"
                "textAlignment"	"east"
                "xpos"	"320"
                "ypos"	"12"
                "zpos"	"3"
                "wide"	"60"
                "tall"	"20"
                "autoResize"	"0"
                "pinCorner"	"0"
                "visible"	"1"
                "enabled"	"1"
                "pin_to_sibling"	"AssistsLabel"
                "pin_corner_to_sibling"	"PIN_BOTTOMRIGHT"
                "pin_to_sibling_corner"	"PIN_BOTTOMRIGHT"
                "if_mvm"
                {
                    "visible"	"0"
                }
            }
            "Destruction"
            {
                "ControlName"	"CExLabel"
                "fieldName"	"Destruction"
                "font"	"Product10Bold"
                "labelText"	"%destruction%"
                "textAlignment"	"west"
                "xpos"	"35"
                "ypos"	"0"
                "zpos"	"3"
                "wide"	"30"
                "tall"	"20"
                "autoResize"	"0"
                "pinCorner"	"0"
                "visible"	"0"
                "enabled"	"0"
                "pin_to_sibling"	"DestructionLabel"
                "pin_corner_to_sibling"	"PIN_TOPRIGHT"
                "pin_to_sibling_corner"	"PIN_TOPRIGHT"
                "if_mvm"
                {
                    "visible"	"0"
                }
            }
            "Destruction2"
            {
                "ControlName"	"CExLabel"
                "fieldName"	"Destruction2"
                "font"	"Product10Bold"
                "labelText"	"%destruction%"
                "textAlignment"	"west"
                "xpos"	"0"
                "ypos"	"0"
                "zpos"	"3"
                "wide"	"30"
                "tall"	"20"
                "autoResize"	"0"
                "pinCorner"	"0"
                "visible"	"1"
                "enabled"	"1"
                "pin_to_sibling"	"Destruction"
                "pin_corner_to_sibling"	"PIN_TOPRIGHT"
                "pin_to_sibling_corner"	"PIN_TOPRIGHT"
                "if_mvm"
                {
                    "visible"	"0"
                }
            }
            "CapturesLabel"
            {
                "ControlName"	"CExLabel"
                "fieldName"	"CapturesLabel"
                "font"	"Product10Bold"
                "labelText"	"#TF_ScoreBoard_CapturesLabel"
                "textAlignment"	"east"
                "xpos"	"0"
                "ypos"	"12"
                "zpos"	"3"
                "wide"	"50"
                "tall"	"20"
                "autoResize"	"0"
                "pinCorner"	"0"
                "visible"	"1"
                "enabled"	"1"
                "fgcolor"   "Purple"
                "pin_to_sibling"	"DamageLabel"
                "pin_corner_to_sibling"	"PIN_BOTTOMRIGHT"
                "pin_to_sibling_corner"	"PIN_BOTTOMRIGHT"
                "if_mvm"
                {
                    "visible"	"0"
                }
            }
            "Captures"
            {
                "ControlName"	"CExLabel"
                "fieldName"	"Captures"
                "font"	"Product10Bold"
                "labelText"	"%captures%"
                "textAlignment"	"west"
                "xpos"	"35"
                "ypos"	"0"
                "zpos"	"3"
                "wide"	"30"
                "tall"	"20"
                "autoResize"	"0"
                "pinCorner"	"0"
                "visible"	"0"
                "enabled"	"0"
                "pin_to_sibling"	"CapturesLabel"
                "pin_corner_to_sibling"	"PIN_TOPRIGHT"
                "pin_to_sibling_corner"	"PIN_TOPRIGHT"
                "if_mvm"
                {
                    "visible"	"0"
                }
            }
            "Captures2"
            {
                "ControlName"	"CExLabel"
                "fieldName"	"Captures2"
                "font"	"Product10Bold"
                "labelText"	"%captures%"
                "textAlignment"	"west"
                "xpos"	"0"
                "ypos"	"0"
                "zpos"	"3"
                "wide"	"30"
                "tall"	"20"
                "autoResize"	"0"
                "pinCorner"	"0"
                "visible"	"1"
                "enabled"	"1"
                "fgcolor"   "Purple"
                "pin_to_sibling"	"Captures"
                "pin_corner_to_sibling"	"PIN_TOPRIGHT"
                "pin_to_sibling_corner"	"PIN_TOPRIGHT"
                "if_mvm"
                {
                    "visible"	"0"
                }
            }
            "DefensesLabel"
            {
                "ControlName"	"CExLabel"
                "fieldName"	"DefensesLabel"
                "font"	"Product10Bold"
                "labelText"	"#TF_ScoreBoard_DefensesLabel"
                "textAlignment"	"east"
                "xpos"	"0"
                "ypos"	"12"
                "zpos"	"3"
                "wide"	"50"
                "tall"	"20"
                "autoResize"	"0"
                "pinCorner"	"0"
                "visible"	"1"
                "enabled"	"1"
                "pin_to_sibling"	"SupportLabel"
                "pin_corner_to_sibling"	"PIN_BOTTOMRIGHT"
                "pin_to_sibling_corner"	"PIN_BOTTOMRIGHT"
                "if_mvm"
                {
                    "visible"	"0"
                }
            }
            "Defenses"
            {
                "ControlName"	"CExLabel"
                "fieldName"	"Defenses"
                "font"	"Product10Bold"
                "labelText"	"%defenses%"
                "textAlignment"	"west"
                "xpos"	"35"
                "ypos"	"0"
                "zpos"	"3"
                "wide"	"30"
                "tall"	"20"
                "autoResize"	"0"
                "pinCorner"	"0"
                "visible"	"0"
                "enabled"	"0"
                "pin_to_sibling"	"DefensesLabel"
                "pin_corner_to_sibling"	"PIN_TOPRIGHT"
                "pin_to_sibling_corner"	"PIN_TOPRIGHT"
                "if_mvm"
                {
                    "visible"	"0"
                }
            }
            "Defenses2"
            {
                "ControlName"	"CExLabel"
                "fieldName"	"Defenses2"
                "font"	"Product10Bold"
                "labelText"	"%defenses%"
                "textAlignment"	"west"
                "xpos"	"0"
                "ypos"	"0"
                "zpos"	"3"
                "wide"	"30"
                "tall"	"20"
                "autoResize"	"0"
                "pinCorner"	"0"
                "visible"	"1"
                "enabled"	"1"
                "pin_to_sibling"	"Defenses"
                "pin_corner_to_sibling"	"PIN_TOPRIGHT"
                "pin_to_sibling_corner"	"PIN_TOPRIGHT"
                "if_mvm"
                {
                    "visible"	"0"
                }
            }
            "DominationLabel"
            {
                "ControlName"	"CExLabel"
                "fieldName"	"DominationLabel"
                "font"	"Product10Bold"
                "labelText"	"#TF_ScoreBoard_DominationLabel"
                "textAlignment"	"east"
                "xpos"	"80"
                "ypos"	"0"
                "zpos"	"3"
                "wide"	"55"
                "tall"	"20"
                "autoResize"	"0"
                "pinCorner"	"0"
                "visible"	"1"
                "enabled"	"1"
                "fgcolor"   "LightOrange"
                "pin_to_sibling"	"AssistsLabel"
                "pin_corner_to_sibling"	"PIN_TOPRIGHT"
                "pin_to_sibling_corner"	"PIN_TOPRIGHT"
                "if_mvm"
                {
                    "visible"	"0"
                }
            }
            "Domination"
            {
                "ControlName"	"CExLabel"
                "fieldName"	"Domination"
                "font"	"Product10Bold"
                "labelText"	"%dominations%"
                "textAlignment"	"west"
                "xpos"	"35"
                "ypos"	"0"
                "zpos"	"3"
                "wide"	"30"
                "tall"	"20"
                "autoResize"	"0"
                "pinCorner"	"0"
                "visible"	"0"
                "enabled"	"0"
                "pin_to_sibling"	"DominationLabel"
                "pin_corner_to_sibling"	"PIN_TOPRIGHT"
                "pin_to_sibling_corner"	"PIN_TOPRIGHT"
                "if_mvm"
                {
                    "visible"	"0"
                }
            }
            "Domination2"
            {
                "ControlName"	"CExLabel"
                "fieldName"	"Domination2"
                "font"	"Product10Bold"
                "labelText"	"%dominations%"
                "textAlignment"	"west"
                "xpos"	"0"
                "ypos"	"0"
                "zpos"	"3"
                "wide"	"30"
                "tall"	"20"
                "autoResize"	"0"
                "pinCorner"	"0"
                "visible"	"1"
                "enabled"	"1"
                "fgcolor"   "LightOrange"
                "pin_to_sibling"	"Domination"
                "pin_corner_to_sibling"	"PIN_TOPRIGHT"
                "pin_to_sibling_corner"	"PIN_TOPRIGHT"
                "if_mvm"
                {
                    "visible"	"0"
                }
            }
            "RevengeLabel"
            {
                "ControlName"	"CExLabel"
                "fieldName"	"RevengeLabel"
                "font"	"Product10Bold"
                "labelText"	"#TF_ScoreBoard_RevengeLabel"
                "textAlignment"	"east"
                "xpos"	"80"
                "ypos"	"0"
                "zpos"	"3"
                "wide"	"50"
                "tall"	"20"
                "autoResize"	"0"
                "pinCorner"	"0"
                "visible"	"1"
                "enabled"	"1"
                "pin_to_sibling"	"DominationLabel"
                "pin_corner_to_sibling"	"PIN_TOPRIGHT"
                "pin_to_sibling_corner"	"PIN_TOPRIGHT"
                "if_mvm"
                {
                    "visible"	"0"
                }
            }
            "Revenge"
            {
                "ControlName"	"CExLabel"
                "fieldName"	"Revenge"
                "font"	"Product10Bold"
                "labelText"	"%Revenge%"
                "textAlignment"	"west"
                "xpos"	"35"
                "ypos"	"0"
                "zpos"	"3"
                "wide"	"30"
                "tall"	"20"
                "autoResize"	"0"
                "pinCorner"	"0"
                "visible"	"0"
                "enabled"	"0"
                "pin_to_sibling"	"RevengeLabel"
                "pin_corner_to_sibling"	"PIN_TOPRIGHT"
                "pin_to_sibling_corner"	"PIN_TOPRIGHT"
                "if_mvm"
                {
                    "visible"	"0"
                }
            }
            "Revenge2"
            {
                "ControlName"	"CExLabel"
                "fieldName"	"Revenge2"
                "font"	"Product10Bold"
                "labelText"	"%Revenge%"
                "textAlignment"	"west"
                "xpos"	"0"
                "ypos"	"0"
                "zpos"	"3"
                "wide"	"30"
                "tall"	"20"
                "autoResize"	"0"
                "pinCorner"	"0"
                "visible"	"1"
                "enabled"	"1"
                "pin_to_sibling"	"Revenge"
                "pin_corner_to_sibling"	"PIN_TOPRIGHT"
                "pin_to_sibling_corner"	"PIN_TOPRIGHT"
                "if_mvm"
                {
                    "visible"	"0"
                }
            }
            "HealingLabel"
            {
                "ControlName"	"CExLabel"
                "fieldName"	"HealingLabel"
                "font"	"Product10Bold"
                "labelText"	"#TF_ScoreBoard_HealingLabel"
                "textAlignment"	"east"
                "xpos"	"0"
                "ypos"	"12"
                "zpos"	"3"
                "wide"	"50"
                "tall"	"20"
                "autoResize"	"0"
                "pinCorner"	"0"
                "visible"	"1"
                "enabled"	"1"
                "fgcolor"   "LightGreen"
                "pin_to_sibling"	"DominationLabel"
                "pin_corner_to_sibling"	"PIN_BOTTOMRIGHT"
                "pin_to_sibling_corner"	"PIN_BOTTOMRIGHT"
                "if_mvm"
                {
                    "font"	"Product10Bold"
                    "xpos"	"0"
                    "ypos"	"20"
                    "pin_to_sibling"	"AssistsLabel"
                    "pin_corner_to_sibling"	"PIN_BOTTOMRIGHT"
                    "pin_to_sibling_corner"	"PIN_BOTTOMRIGHT"
                }
            }
            "Healing"
            {
                "ControlName"	"CExLabel"
                "fieldName"	"Healing"
                "font"	"Product10Bold"
                "labelText"	"%healing%"
                "textAlignment"	"west"
                "xpos"	"35"
                "ypos"	"0"
                "zpos"	"3"
                "wide"	"30"
                "tall"	"20"
                "autoResize"	"0"
                "pinCorner"	"0"
                "visible"	"0"
                "enabled"	"0"
                "pin_to_sibling"	"HealingLabel"
                "pin_corner_to_sibling"	"PIN_TOPRIGHT"
                "pin_to_sibling_corner"	"PIN_TOPRIGHT"
            }
            "Healing2"
            {
                "ControlName"	"CExLabel"
                "fieldName"	"Healing2"
                "font"	"Product10Bold"
                "labelText"	"%healing%"
                "textAlignment"	"west"
                "xpos"	"0"
                "ypos"	"0"
                "zpos"	"3"
                "wide"	"30"
                "tall"	"20"
                "autoResize"	"0"
                "pinCorner"	"0"
                "visible"	"1"
                "enabled"	"1"
                "fgcolor"   "LightGreen"
                "pin_to_sibling"	"Healing"
                "pin_corner_to_sibling"	"PIN_TOPRIGHT"
                "pin_to_sibling_corner"	"PIN_TOPRIGHT"
                "if_mvm"
                {
                    "font"	"Product10Bold"
                }
            }
            "InvulnLabel"
            {
                "ControlName"	"CExLabel"
                "fieldName"	"InvulnLabel"
                "font"	"Product10Bold"
                "labelText"	"#TF_ScoreBoard_InvulnLabel"
                "textAlignment"	"east"
                "xpos"	"0"
                "ypos"	"12"
                "zpos"	"3"
                "wide"	"50"
                "tall"	"20"
                "autoResize"	"0"
                "pinCorner"	"0"
                "visible"	"1"
                "enabled"	"1"
                "pin_to_sibling"	"RevengeLabel"
                "pin_corner_to_sibling"	"PIN_BOTTOMRIGHT"
                "pin_to_sibling_corner"	"PIN_BOTTOMRIGHT"
                "if_mvm"
                {
                    "font"	"Product12Bold"
                    "ypos"	"20"
                }
            }
            "Invuln"
            {
                "ControlName"	"CExLabel"
                "fieldName"	"Invuln"
                "font"	"Product10Bold"
                "labelText"	"%invulns%"
                "textAlignment"	"west"
                "xpos"	"35"
                "ypos"	"0"
                "zpos"	"3"
                "wide"	"30"
                "tall"	"20"
                "autoResize"	"0"
                "pinCorner"	"0"
                "visible"	"0"
                "enabled"	"0"
                "pin_to_sibling"	"InvulnLabel"
                "pin_corner_to_sibling"	"PIN_TOPRIGHT"
                "pin_to_sibling_corner"	"PIN_TOPRIGHT"
            }
            "Invuln2"
            {
                "ControlName"	"CExLabel"
                "fieldName"	"Invuln2"
                "font"	"Product10Bold"
                "labelText"	"%invulns%"
                "textAlignment"	"west"
                "xpos"	"0"
                "ypos"	"0"
                "zpos"	"3"
                "wide"	"30"
                "tall"	"20"
                "autoResize"	"0"
                "pinCorner"	"0"
                "visible"	"1"
                "enabled"	"1"
                "pin_to_sibling"	"Invuln"
                "pin_corner_to_sibling"	"PIN_TOPRIGHT"
                "pin_to_sibling_corner"	"PIN_TOPRIGHT"
                "if_mvm"
                {
                    "font"	"Product10Bold"
                }
            }
            "TeleportsLabel"
            {
                "ControlName"	"CExLabel"
                "fieldName"	"TeleportsLabel"
                "font"	"Product10Bold"
                "labelText"	"#TF_ScoreBoard_TeleportsLabel"
                "textAlignment"	"east"
                "xpos"	"0"
                "ypos"	"12"
                "zpos"	"3"
                "wide"	"50"
                "tall"	"20"
                "autoResize"	"0"
                "pinCorner"	"0"
                "visible"	"1"
                "enabled"	"1"
                "pin_to_sibling"	"DefensesLabel"
                "pin_corner_to_sibling"	"PIN_BOTTOMRIGHT"
                "pin_to_sibling_corner"	"PIN_BOTTOMRIGHT"
                "if_mvm"
                {
                    "font"	"Product12Bold"
                    "xpos"	"90"
                    "ypos"	"0"
                    "pin_to_sibling"	"AssistsLabel"
                    "pin_corner_to_sibling"	"PIN_BOTTOMRIGHT"
                    "pin_to_sibling_corner"	"PIN_BOTTOMRIGHT"
                }
            }
            "Teleports"
            {
                "ControlName"	"CExLabel"
                "fieldName"	"Teleports"
                "font"	"Product10Bold"
                "labelText"	"%teleports%"
                "textAlignment"	"west"
                "xpos"	"35"
                "ypos"	"0"
                "zpos"	"3"
                "wide"	"30"
                "tall"	"20"
                "autoResize"	"0"
                "pinCorner"	"0"
                "visible"	"0"
                "enabled"	"0"
                "pin_to_sibling"	"TeleportsLabel"
                "pin_corner_to_sibling"	"PIN_TOPRIGHT"
                "pin_to_sibling_corner"	"PIN_TOPRIGHT"
            }
            "Teleports2"
            {
                "ControlName"	"CExLabel"
                "fieldName"	"Teleports2"
                "font"	"Product10Bold"
                "labelText"	"%teleports%"
                "textAlignment"	"west"
                "xpos"	"0"
                "ypos"	"0"
                "zpos"	"3"
                "wide"	"30"
                "tall"	"20"
                "autoResize"	"0"
                "pinCorner"	"0"
                "visible"	"1"
                "enabled"	"1"
                "pin_to_sibling"	"Teleports"
                "pin_corner_to_sibling"	"PIN_TOPRIGHT"
                "pin_to_sibling_corner"	"PIN_TOPRIGHT"
                "if_mvm"
                {
                    "font"	"Product10Bold"
                }
            }
            "HeadshotsLabel"
            {
                "ControlName"	"CExLabel"
                "fieldName"	"HeadshotsLabel"
                "font"	"Product10Bold"
                "labelText"	"#TF_ScoreBoard_HeadshotsLabel"
                "textAlignment"	"east"
                "xpos"	"0"
                "ypos"	"12"
                "zpos"	"3"
                "wide"	"50"
                "tall"	"20"
                "autoResize"	"0"
                "pinCorner"	"0"
                "visible"	"1"
                "enabled"	"1"
                "pin_to_sibling"	"HealingLabel"
                "pin_corner_to_sibling"	"PIN_BOTTOMRIGHT"
                "pin_to_sibling_corner"	"PIN_BOTTOMRIGHT"
                "if_mvm"
                {
                    "font"	"Product10Bold"
                    "xpos"	"0"
                    "ypos"	"20"
                    "wide"	"55"
                    "pin_to_sibling"	"TeleportsLabel"
                    "pin_corner_to_sibling"	"PIN_BOTTOMRIGHT"
                    "pin_to_sibling_corner"	"PIN_BOTTOMRIGHT"
                }
            }
            "Headshots"
            {
                "ControlName"	"CExLabel"
                "fieldName"	"Headshots"
                "font"	"Product10Bold"
                "labelText"	"%headshots%"
                "textAlignment"	"west"
                "xpos"	"35"
                "ypos"	"0"
                "zpos"	"3"
                "wide"	"30"
                "tall"	"20"
                "autoResize"	"0"
                "pinCorner"	"0"
                "visible"	"0"
                "enabled"	"0"
                "pin_to_sibling"	"HeadshotsLabel"
                "pin_corner_to_sibling"	"PIN_TOPRIGHT"
                "pin_to_sibling_corner"	"PIN_TOPRIGHT"
            }
            "Headshots2"
            {
                "ControlName"	"CExLabel"
                "fieldName"	"Headshots2"
                "font"	"Product10Bold"
                "labelText"	"%headshots%"
                "textAlignment"	"west"
                "xpos"	"0"
                "ypos"	"0"
                "zpos"	"3"
                "wide"	"30"
                "tall"	"20"
                "autoResize"	"0"
                "pinCorner"	"0"
                "visible"	"1"
                "enabled"	"1"
                "pin_to_sibling"	"Headshots"
                "pin_corner_to_sibling"	"PIN_TOPRIGHT"
                "pin_to_sibling_corner"	"PIN_TOPRIGHT"
                "if_mvm"
                {
                    "font"	"Product10Bold"
                }
            }
            "BackstabsLabel"
            {
                "ControlName"	"CExLabel"
                "fieldName"	"BackstabsLabel"
                "font"	"Product10Bold"
                "labelText"	"#TF_ScoreBoard_BackstabsLabel"
                "textAlignment"	"east"
                "xpos"	"0"
                "ypos"	"12"
                "zpos"	"3"
                "wide"	"50"
                "tall"	"20"
                "autoResize"	"0"
                "pinCorner"	"0"
                "visible"	"1"
                "enabled"	"1"
                "pin_to_sibling"	"InvulnLabel"
                "pin_corner_to_sibling"	"PIN_BOTTOMRIGHT"
                "pin_to_sibling_corner"	"PIN_BOTTOMRIGHT"
                "if_mvm"
                {
                    "font"	"Product10Bold"
                    "ypos"	"20"
                }
            }
            "Backstabs"
            {
                "ControlName"	"CExLabel"
                "fieldName"	"Backstabs"
                "font"	"Product10Bold"
                "labelText"	"%backstabs%"
                "textAlignment"	"west"
                "xpos"	"35"
                "ypos"	"0"
                "zpos"	"3"
                "wide"	"30"
                "tall"	"20"
                "autoResize"	"0"
                "pinCorner"	"0"
                "visible"	"0"
                "enabled"	"0"
                "pin_to_sibling"	"BackstabsLabel"
                "pin_corner_to_sibling"	"PIN_TOPRIGHT"
                "pin_to_sibling_corner"	"PIN_TOPRIGHT"
            }
            "Backstabs2"
            {
                "ControlName"	"CExLabel"
                "fieldName"	"Backstabs2"
                "font"	"Product10Bold"
                "labelText"	"%backstabs%"
                "textAlignment"	"west"
                "xpos"	"0"
                "ypos"	"0"
                "zpos"	"3"
                "wide"	"30"
                "tall"	"20"
                "autoResize"	"0"
                "pinCorner"	"0"
                "visible"	"1"
                "enabled"	"1"
                "pin_to_sibling"	"Backstabs"
                "pin_corner_to_sibling"	"PIN_TOPRIGHT"
                "pin_to_sibling_corner"	"PIN_TOPRIGHT"
                "if_mvm"
                {
                    "font"	"Product10Bold"
                }
            }
            "BonusLabel"
            {
                "ControlName"	"CExLabel"
                "fieldName"	"BonusLabel"
                "font"	"Product10Bold"
                "labelText"	"#TF_ScoreBoard_BonusLabel"
                "textAlignment"	"east"
                "xpos"	"60"
                "ypos"	"0"
                "zpos"	"3"
                "wide"	"50"
                "tall"	"20"
                "autoResize"	"0"
                "pinCorner"	"0"
                "visible"	"1"
                "enabled"	"1"
                "pin_to_sibling"	"SupportLabel"
                "pin_corner_to_sibling"	"PIN_BOTTOMRIGHT"
                "pin_to_sibling_corner"	"PIN_BOTTOMRIGHT"
                "if_mvm"
                {
                    "font"	"Product10Bold"
                    "xpos"	"90"
                    "ypos"	"0"
                    "pin_to_sibling"	"TeleportsLabel"
                    "pin_corner_to_sibling"	"PIN_BOTTOMRIGHT"
                    "pin_to_sibling_corner"	"PIN_BOTTOMRIGHT"
                }
            }
            "Bonus"
            {
                "ControlName"	"CExLabel"
                "fieldName"	"Bonus"
                "font"	"Product10Bold"
                "labelText"	"%bonus%"
                "textAlignment"	"west"
                "xpos"	"35"
                "ypos"	"0"
                "zpos"	"3"
                "wide"	"30"
                "tall"	"20"
                "autoResize"	"0"
                "pinCorner"	"0"
                "visible"	"0"
                "enabled"	"0"
                "pin_to_sibling"	"BonusLabel"
                "pin_corner_to_sibling"	"PIN_TOPRIGHT"
                "pin_to_sibling_corner"	"PIN_TOPRIGHT"
            }
            "Bonus2"
            {
                "ControlName"	"CExLabel"
                "fieldName"	"Bonus2"
                "font"	"Product10Bold"
                "labelText"	"%bonus%"
                "textAlignment"	"west"
                "xpos"	"0"
                "ypos"	"0"
                "zpos"	"3"
                "wide"	"30"
                "tall"	"20"
                "autoResize"	"0"
                "pinCorner"	"0"
                "visible"	"1"
                "enabled"	"1"
                "pin_to_sibling"	"Bonus"
                "pin_corner_to_sibling"	"PIN_TOPRIGHT"
                "pin_to_sibling_corner"	"PIN_TOPRIGHT"
                "if_mvm"
                {
                    "font"	"Product10Bold"
                }
            }
            "SupportLabel"
            {
                "ControlName"	"CExLabel"
                "fieldName"	"SupportLabel"
                "font"	"Product10Bold"
                "labelText"	"#TF_Scoreboard_Support"
                "textAlignment"	"east"
                "xpos"	"80"
                "ypos"	"0"
                "zpos"	"3"
                "wide"	"50"
                "tall"	"20"
                "autoResize"	"0"
                "pinCorner"	"0"
                "visible"	"1"
                "enabled"	"1"
                "pin_to_sibling"	"RevengeLabel"
                "pin_corner_to_sibling"	"PIN_TOPRIGHT"
                "pin_to_sibling_corner"	"PIN_TOPRIGHT"
                "if_mvm"
                {
                    "font"	"Product10Bold"
                    "xpos"	"0"
                    "ypos"	"20"
                    "pin_to_sibling"	"BonusLabel"
                    "pin_corner_to_sibling"	"PIN_BOTTOMRIGHT"
                    "pin_to_sibling_corner"	"PIN_BOTTOMRIGHT"
                }
            }
            "Support"
            {
                "ControlName"	"CExLabel"
                "fieldName"	"Support"
                "font"	"Product10Bold"
                "labelText"	"%support%"
                "textAlignment"	"west"
                "xpos"	"35"
                "ypos"	"0"
                "zpos"	"3"
                "wide"	"30"
                "tall"	"20"
                "autoResize"	"0"
                "pinCorner"	"0"
                "visible"	"0"
                "enabled"	"0"
                "pin_to_sibling"	"SupportLabel"
                "pin_corner_to_sibling"	"PIN_TOPRIGHT"
                "pin_to_sibling_corner"	"PIN_TOPRIGHT"
            }
            "Support2"
            {
                "ControlName"	"CExLabel"
                "fieldName"	"Support2"
                "font"	"Product10Bold"
                "labelText"	"%support%"
                "textAlignment"	"west"
                "xpos"	"0"
                "ypos"	"0"
                "zpos"	"3"
                "wide"	"30"
                "tall"	"20"
                "autoResize"	"0"
                "pinCorner"	"0"
                "visible"	"1"
                "enabled"	"1"
                "pin_to_sibling"	"Support"
                "pin_corner_to_sibling"	"PIN_TOPRIGHT"
                "pin_to_sibling_corner"	"PIN_TOPRIGHT"
                "if_mvm"
                {
                    "font"	"Product10Bold"
                }
            }
            "DamageLabel"
            {
                "ControlName"	"CExLabel"
                "fieldName"	"DamageLabel"
                "font"	"Product10Bold"
                "labelText"	"#TF_Scoreboard_Damage"
                "textAlignment"	"east"
                "xpos"	"0"
                "ypos"	"12"
                "zpos"	"3"
                "wide"	"50"
                "tall"	"20"
                "autoResize"	"0"
                "pinCorner"	"0"
                "visible"	"1"
                "enabled"	"1"
                "fgcolor"   "arekkRedS"
                "pin_to_sibling"	"AssistsLabel"
                "pin_corner_to_sibling"	"PIN_BOTTOMRIGHT"
                "pin_to_sibling_corner"	"PIN_BOTTOMRIGHT"
                "if_mvm"
                {
                    "font"	"Product10Bold"
                    "ypos"	"20"
                }
            }
            "Damage"
            {
                "ControlName"	"CExLabel"
                "fieldName"	"Damage"
                "font"	"Product10Bold"
                "labelText"	"%damage%"
                "textAlignment"	"west"
                "xpos"	"35"
                "ypos"	"0"
                "zpos"	"3"
                "wide"	"30"
                "tall"	"20"
                "autoResize"	"0"
                "pinCorner"	"0"
                "visible"	"0"
                "enabled"	"0"
                "pin_to_sibling"	"DamageLabel"
                "pin_corner_to_sibling"	"PIN_TOPRIGHT"
                "pin_to_sibling_corner"	"PIN_TOPRIGHT"
            }
            "Damage2"
            {
                "ControlName"	"CExLabel"
                "fieldName"	"Damage2"
                "font"	"Product10Bold"
                "labelText"	"%damage%"
                "textAlignment"	"west"
                "xpos"	"0"
                "ypos"	"0"
                "zpos"	"3"
                "wide"	"30"
                "tall"	"20"
                "autoResize"	"0"
                "pinCorner"	"0"
                "visible"	"1"
                "enabled"	"1"
                "fgcolor"   "arekkRedS"
                "pin_to_sibling"	"Damage"
                "pin_corner_to_sibling"	"PIN_TOPRIGHT"
                "pin_to_sibling_corner"	"PIN_TOPRIGHT"
                "if_mvm"
                {
                    "font"	"Product10Bold"
                }
            }
	}
	"MvMScoreboard"
	{
		"ControlName"	"CTFHudMannVsMachineScoreboard"
		"fieldName"	"MvMScoreboard"
		"xpos"	"c-266"
		"ypos"	"0"
		"zpos"	"10"
		"wide"	"f0"
		"tall"	"480"
		"visible"	"0"
		"enabled"	"1"
		"verbose"	"1"
		"if_mvm"
		{
			"visible"	"1"
		}
	}
}

